hpr_ditch_detection:
    merge_lines: False
    filter_background: 
        threshold_factor: 3.  # number of sigmas to reject it as background
        threshold_value: .5
        background_estimation_method: median
        gaussian_sigma: null
    buffer_zone: 
        distance: 30.  # distance around a line segment to buffer (in units of Coordinate Reference System)

line_segment_detection:
    rho_tolerance: 10.  # (in pixels)
    theta_tolerance: 5. # (in degrees)
    Hough lines:
        rho_resolution: 1  # (in pixels)
        theta_resolution: .1  # (in degrees)
        threshold: 30  # minimal number of pixels to form a line segment
        minLineLength: 50.  # minimal length of a line segment (in pixels)
        maxLineGap: 30.  # maximal gap distance to consider as one line segment (in pixel)